package com.fangger.dao.mysql.model;

public class AppPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app-permission.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app-permission.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app-permission.perssion_id
     *
     * @mbggenerated
     */
    private Integer perssionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app-permission.Id
     *
     * @return the value of app-permission.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app-permission.Id
     *
     * @param id the value for app-permission.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app-permission.app_id
     *
     * @return the value of app-permission.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app-permission.app_id
     *
     * @param appId the value for app-permission.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app-permission.perssion_id
     *
     * @return the value of app-permission.perssion_id
     *
     * @mbggenerated
     */
    public Integer getPerssionId() {
        return perssionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app-permission.perssion_id
     *
     * @param perssionId the value for app-permission.perssion_id
     *
     * @mbggenerated
     */
    public void setPerssionId(Integer perssionId) {
        this.perssionId = perssionId;
    }
}