package com.fangger.dao.mysql.mapper;

import com.fangger.dao.mysql.model.AppPermission;
import com.fangger.dao.mysql.model.AppPermissionExample;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int countByExample(AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int deleteByExample(AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int insert(AppPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int insertSelective(AppPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    List<AppPermission> selectByExample(AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    AppPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppPermission record, @Param("example") AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppPermission record, @Param("example") AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app-permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppPermission record);

    int insertBath(List<AppPermission> appPermissionList);
}